### ISSUE TITLE
Shard currency system

### ISSUE THREAD

**Issue by lucasmillanm** [keykey7/fabbwled#215] opened 2023-09-04 14:49 UTC
**Is your feature request related to a problem? Please describe.**
#209 
```
Be able to gain shards or lose shards
```

**Describe the solution you'd like**
- Character has shards
- Depending on the section add or subtract the given amount of shards

**Comment by keykey7** [comment] 2023-09-11 15:02
Additionally enforce the game rules: shards can never become negative.

**Comment by Nilstrieb** [comment] 2023-09-25 15:24
duplicate of #10

**Closed by Nilstrieb** 2023-09-25 15:24 UTC
Labels: enhancement
